avoid the zealous replacing of ampersands
Clustaar/clustaar.schemas pull request #37
Opened 2019-10-16 14:59 UTC by glebourgeois

as discussed.
Vu aussi avec Paul : ils utilisent parfois les `&` dans les textes, donc faudrait a minima qu'ils s'affichent joliment et pas en entité html.

2019-10-16 16:08 UTC, bjamet requested changes
et mes protection des balises <\br> et autre ??? les '>' sont aussi modifié...
voit avec le front quels balises ils supportent pour pas tous les niquer

2019-10-17 06:36 UTC, glebourgeois commented
```python
bleach.sanitizer.ALLOWED_TAGS = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code', 'em', 'i', 'li', 'ol', 'strong', 'ul']
```

C'est la liste par défaut ; on peut ajouter ce qu'on veut. 

Mais franchement, le `<br/>` je trouve qu'on ne devrait pas supporter, on fait des messages de bot, pas des pages web. C'est assez crade d'avoir un très long message avec des <br/>, il faut privilégier une succession de courts messages.

La liste par défaut me semble absolument parfaite, elle permet de faire du gras, italique et de faire des puces, ainsi que des liens. Je ne pense pas qu'il serait pertinent d'aller plus loin.

2019-10-17 07:45 UTC, bjamet commented
dans une meme bulle il y a parfoi besoin d'un peut de cohérence, et un retour a la ligne ca fait pas de mal ... en tout cas j'ai communiqué à Paul de cette possibilité, donc c probabalement utilisé a certain endroits

2019-10-17 08:48 UTC, aschafers commented
Et je me demande si c'est pas utilisé dans intercom avec les <h1> et compagnie.

2019-10-17 09:16 UTC, aschafers commented
dans intercom on transform les google custom search en html 

```def to_html(results):
    """
    Convert GoogleSearchResult to html in SendTextAction

    Args:
         results ([GoogleSearchResult]): some google search results

    Returns: [SendTextAction]
    """
    text_actions = []

    for result in results:
        doc, tag, text = Doc().tagtext()

        with tag(
            "div", klass="google-custom-search-result"
        ):  # TODO: dont forget to remove (IDF bot fix)
            with tag("h1"):
                with tag("a", href=result.url):
                    text(result.title)
            with tag("p"):
                text(result.body)

        text_actions.append(SendTextAction(alternatives=[doc.getvalue()]))

    return text_actions```

2019-10-17 10:33 UTC, bjamet commented
> dans intercom on transform les google custom search en html
> 
> ```
>     """
>     Convert GoogleSearchResult to html in SendTextAction
> 
>     Args:
>          results ([GoogleSearchResult]): some google search results
> 
>     Returns: [SendTextAction]
>     """
>     text_actions = []
> 
>     for result in results:
>         doc, tag, text = Doc().tagtext()
> 
>         with tag(
>             "div", klass="google-custom-search-result"
>         ):  # TODO: dont forget to remove (IDF bot fix)
>             with tag("h1"):
>                 with tag("a", href=result.url):
>                     text(result.title)
>             with tag("p"):
>                 text(result.body)
> 
>         text_actions.append(SendTextAction(alternatives=[doc.getvalue()]))
> 
>     return text_actions```
> ```

c'est hors sujet ... c transformé en html pour que intercom l'interprete bien ..; ca passe pas par le pre_load de lupin

2019-10-17 12:04 UTC, aschafers commented
je dis pas le contraire ^^ je voulais exprimer le potentiel manque de coherence a ne pas vouloir géré le alors que certai bot l'utilise c'est tous.

2019-10-17 12:20 UTC, glebourgeois commented
> dans une meme bulle il y a parfoi besoin d'un peut de cohérence, et un retour a la ligne ca fait pas de mal ... en tout cas j'ai communiqué à Paul de cette possibilité, donc c probabalement utilisé a certain endroits

Je vais lui demander si c'est le cas.

2019-10-17 13:46 UTC, glebourgeois commented
Vu avec Paul, les `<br>` sont apparemment très utilisés...
![Capture d’écran de 2019-10-17 15-44-31](https://user-images.githubusercontent.com/713089/67014418-1d418e00-f0f5-11e9-9179-8f5ce04b65f8.png)

Pas le choix du coup, j'ai fait un commit pour les gérer. 
Good for you?

2019-10-17 20:35 UTC, aschafers approved these changes

2019-10-18 07:18 UTC, bjamet commented
avec uvon, on a trouvé la liste des balise que angular ne sanetalize pas, et qui donc jusqu'à peut était supporté par la plateforme.

LEsquelles il faudrait ajouter dans la liste des tag ? 

`// Safe Void Elements - HTML5
// http://dev.w3.org/html5/spec/Overview.html#void-elements
const VOID_ELEMENTS = tagSet('area,br,col,hr,img,wbr');

// Elements that you can, intentionally, leave open (and which close themselves)
// http://dev.w3.org/html5/spec/Overview.html#optional-tags
const OPTIONAL_END_TAG_BLOCK_ELEMENTS = tagSet('colgroup,dd,dt,li,p,tbody,td,tfoot,th,thead,tr');
const OPTIONAL_END_TAG_INLINE_ELEMENTS = tagSet('rp,rt');
const OPTIONAL_END_TAG_ELEMENTS =
    merge(OPTIONAL_END_TAG_INLINE_ELEMENTS, OPTIONAL_END_TAG_BLOCK_ELEMENTS);

// Safe Block Elements - HTML5
const BLOCK_ELEMENTS = merge(
    OPTIONAL_END_TAG_BLOCK_ELEMENTS,
    tagSet(
        'address,article,' +
        'aside,blockquote,caption,center,del,details,dialog,dir,div,dl,figure,figcaption,footer,h1,h2,h3,h4,h5,' +
        'h6,header,hgroup,hr,ins,main,map,menu,nav,ol,pre,section,summary,table,ul'));

// Inline Elements - HTML5
const INLINE_ELEMENTS = merge(
    OPTIONAL_END_TAG_INLINE_ELEMENTS,
    tagSet(
        'a,abbr,acronym,audio,b,' +
        'bdi,bdo,big,br,cite,code,del,dfn,em,font,i,img,ins,kbd,label,map,mark,picture,q,ruby,rp,rt,s,' +
        'samp,small,source,span,strike,strong,sub,sup,time,track,tt,u,var,video'));

export const VALID_ELEMENTS =
    merge(VOID_ELEMENTS, BLOCK_ELEMENTS, INLINE_ELEMENTS, OPTIONAL_END_TAG_ELEMENTS);`

2019-10-18 07:22 UTC, bjamet commented
proposition de yvon plutot que bleach :

https://pypi.org/project/html-sanitizer/

2019-10-18 07:34 UTC, glebourgeois commented
Je pense que notre liste est bien là, dans le contexte d'une mini-réponse de bot (bleach + br).
On gère les besoins de base pour un minimum de mise en page (et sans risque de péter le rendu du webchat ;) ).

> https://pypi.org/project/html-sanitizer/

oui je l'avais vu quand j'ai cherché une lib, mais le projet est presque mort, et très peu utilisé. En comparaison, `bleach` est très vivant, et très largement diffusé avec une vraie communauté.

2019-10-18 08:14 UTC, bjamet commented
des cas vu dans la base de prod : 
named captured groups for example : \"(?P<number>\\d{5})\".
(c'est du regex, a vérifeir que ca s'affiche bien )
 sinon je cède, il n'y a que des balise br/a/i effectivement utilisé en prod

2019-10-18 08:15 UTC, bjamet approved these changes

2019-10-18 14:53 UTC, merged