Add schema for zendesk
Clustaar/clustaar.schemas pull request #4
Opened 2018-06-28 12:44 UTC by aschafers

2018-06-28 13:46 UTC, holinnn requested changes

2018-06-28 13:46 UTC, holinnn commented on src/clustaar/schemas/constants.py
> +ZENDESK_TAG_MAX_LENGTH = 80
En prefix je mettrais `ZENDESK_TICKET` plutôt que seulement `ZENDESK` qui est un peu large non ?

2018-06-28 13:46 UTC, holinnn commented on src/clustaar/schemas/models.py
> +    "ticket_type subject description assignee_id group_id tags name email phone_number"
Ici on va extraire les champs qui sont plus en rapport à l'utilisateur zendesk.
Ca permet d'avoir les champs du ticket au premier niveau et ceux de l'utilisateur regrouper dans un objet imbriqué.
Le json final de l'action aurait une forme un peu dans ce genre : 
```
{
     "assigneeID": "...",
     "user": {
          "name": "...",
          "email": "..."
     }
}
```

Donc on aurait 2 modèles : 
- CreateZendeskTicketAction (qui aurait à la place d'email, phone_number et name, un champs user)
- et ZendeskUser

2018-06-29 07:23 UTC, holinnn requested changes

2018-06-29 07:23 UTC, holinnn commented on src/clustaar/schemas/models.py
> +ZendeskUser = model("ZendeskUser", "email name")
phone_number devrait pas être ici aussi ?

2018-06-29 10:13 UTC, aschafers commented on src/clustaar/schemas/models.py
> +ZendeskUser = model("ZendeskUser", "email name")
Si bien jouer!

2018-07-03 12:42 UTC, merged